import type { WebsiteContent, WebsiteTemplate, WebsiteTheme } from '@/lib/website';
import Link from 'next/link';
import { FaFacebookF, FaInstagram, FaWhatsapp } from 'react-icons/fa6';
import GalleryCarousel from './GalleryCarousel';
/* User-managed images come from a dynamic public media library. */
/* eslint-disable @next/next/no-img-element */
function whatsappLink(value: string) { const digits=value.replace(/\D/g,''); if(!digits)return ''; const international=digits.startsWith('56')?digits:digits.length===9?`56${digits}`:digits; return `https://wa.me/${international}`; }
function socialLink(value: string, network: 'facebook'|'instagram') { const clean=value.trim(); if(!clean)return ''; if(/^https?:\/\//i.test(clean))return clean; if(/^(?:www\.)?(?:facebook|instagram)\.com\//i.test(clean))return `https://${clean}`; return `https://www.${network}.com/${clean.replace(/^@/,'').replace(/^\/+|\/+$/g,'')}`; }
export default function WebsiteRenderer({ name, template, content, theme, logo, hero, gallery = [] }: { name: string; template: WebsiteTemplate; content: WebsiteContent; theme: WebsiteTheme; logo?: string | null; hero?: string | null; gallery?: string[] }) {
 const style = { '--site-primary': theme.primary, '--site-accent': theme.accent, '--site-bg': theme.background, '--site-text': theme.text } as React.CSSProperties;
 return <div className={`community-site template-${template}`} style={style}>
  <header>{logo ? <img src={logo} alt={`Logo de ${name}`} /> : <span className="site-monogram">{name.slice(0,2).toUpperCase()}</span>}<strong>{name}</strong><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Comunidad</a>{gallery.length>0&&<a href="#galeria">Galería</a>}<a href="#noticias">Noticias</a><a href="#contacto">Contacto</a></nav></header>
  <section className="site-hero" style={hero ? { backgroundImage: `linear-gradient(90deg,rgba(5,20,35,.82),rgba(5,20,35,.18)),url(${hero})` } : undefined}><div><span>JUNTA DE VECINOS</span><h1>{content.title}</h1><p>{content.subtitle}</p><a href="#contacto">Participa con nosotros</a></div></section>
  <main><section id="nosotros" className="site-about"><div><span>NUESTRA COMUNIDAD</span><h2>{content.aboutTitle}</h2><p>{content.about}</p></div>{gallery[0] && <img src={gallery[0]} alt="Actividad de la comunidad" />}</section>
  <section id="servicios" className="site-services"><span>TRABAJO VECINAL</span><h2>{content.servicesTitle}</h2><div>{content.services.map((service, index) => <article key={`${service}-${index}`}><b>0{index+1}</b><h3>{service}</h3><p>Una iniciativa abierta para mejorar la vida de quienes forman parte de nuestro barrio.</p></article>)}</div></section>
  <GalleryCarousel images={gallery} name={name}/>
  <section className="site-news" id="noticias"><div className="site-news-heading"><span>ACTUALIDAD VECINAL</span><h2>{content.newsTitle}</h2><p>{content.news}</p></div>{content.newsItems?.length ? <div className="site-news-grid">{content.newsItems.map((item) => <article key={item.id}>{item.image ? <img src={item.image} alt={item.title} /> : <div className="news-image-placeholder" aria-hidden="true">J</div>}<div><span>{item.category || 'Comunidad'} · {item.date ? new Intl.DateTimeFormat('es-CL').format(new Date(`${item.date}T12:00:00`)) : 'Sin fecha'}</span><h3>{item.title}</h3><p>{item.summary}</p></div></article>)}</div> : null}</section>
  <section id="contacto" className="site-contact"><div><span>CONTACTO</span><h2>{content.contactTitle}</h2><p>{content.contact}</p><div className="site-social-links">{whatsappLink(content.whatsapp??'')&&<a className="social-whatsapp" href={whatsappLink(content.whatsapp)} target="_blank" rel="noopener noreferrer" aria-label={`WhatsApp de ${name}`}><FaWhatsapp aria-hidden="true"/><span>WhatsApp</span></a>}{socialLink(content.facebook??'','facebook')&&<a className="social-facebook" href={socialLink(content.facebook,'facebook')} target="_blank" rel="noopener noreferrer" aria-label={`Facebook de ${name}`}><FaFacebookF aria-hidden="true"/><span>Facebook</span></a>}{socialLink(content.instagram??'','instagram')&&<a className="social-instagram" href={socialLink(content.instagram,'instagram')} target="_blank" rel="noopener noreferrer" aria-label={`Instagram de ${name}`}><FaInstagram aria-hidden="true"/><span>Instagram</span></a>}</div></div>{content.address&&<address>{content.address}</address>}</section></main>
  <footer><strong>{name}</strong><span><Link href="/">Creado con JuntAPP</Link><i> · </i><a href="https://www.purocode.com/" target="_blank" rel="noopener noreferrer">by PuroCode</a></span></footer>
 </div>;
}
