'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import type { PollProposal, Profile } from '@/lib/types';

interface PollOption { id: string; text: string; votes: number }
interface EnrichedPoll { id: string; title: string; description: string; active: boolean; options: PollOption[]; hasVoted: boolean; created_at: string }

export default function VotacionesClient({ polls, currentProfile, proposals }: { polls: EnrichedPoll[]; currentProfile: Profile; proposals: PollProposal[] }) {
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState('');
  const [voting, setVoting] = useState(false);
  const [options, setOptions] = useState(['', '']);
  const [error, setError] = useState('');
  const [proposalMessage, setProposalMessage] = useState('');
  const [reviewingProposal, setReviewingProposal] = useState<string | null>(null);
  const router = useRouter();
  const isDirigente = currentProfile.role === 'dirigente';
  const activePoll = polls.find((poll) => poll.active);
  const pastPolls = polls.filter((poll) => !poll.active);

  async function handleVote(event: React.FormEvent) { event.preventDefault(); if (!activePoll || !selected) return; setVoting(true); const { error: voteError } = await createClient().from('votes').insert({ user_id: currentProfile.id, poll_id: activePoll.id, option_id: selected }); if (voteError) alert(voteError.code === '23505' ? 'Ya has emitido tu voto.' : voteError.message); else router.refresh(); setVoting(false); }
  async function handleCreatePoll(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const clean = options.map((item) => item.trim()).filter(Boolean); if (clean.length < 2) { setError('Agrega al menos dos alternativas.'); return; } setLoading(true); setError(''); const form = new FormData(event.currentTarget); const title = String(form.get('title')).trim(); const description = String(form.get('description')).trim(); if (!isDirigente) { const response = await fetch('/api/polls/proposals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, options: clean }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? 'No fue posible enviar la propuesta.'); else { setShowModal(false); setOptions(['', '']); setProposalMessage('Propuesta enviada a la directiva para revisión.'); router.refresh(); } setLoading(false); return; } const supabase = createClient(); if (activePoll) { setError('Cierra la votación activa antes de publicar una nueva.'); setLoading(false); return; } const { error: insertError } = await supabase.from('polls').insert({ title, description, junta_id: currentProfile.junta_id, active: true, options: clean.map((text, index) => ({ id: `opt-${index + 1}`, text })) }); if (insertError) setError(insertError.message); else { setShowModal(false); setOptions(['', '']); router.refresh(); } setLoading(false); }
  async function reviewProposal(proposal: PollProposal, decision: 'approve' | 'reject') { const reason = decision === 'reject' ? window.prompt('Indica el motivo del rechazo:')?.trim() : undefined; if (decision === 'reject' && !reason) return; setReviewingProposal(proposal.id); setProposalMessage(''); const response = await fetch(`/api/polls/proposals/${proposal.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision, reason }) }); const result = await response.json(); setReviewingProposal(null); if (!response.ok) { setProposalMessage(result.error ?? 'No fue posible revisar la propuesta.'); return; } setProposalMessage(decision === 'approve' ? 'Propuesta aprobada y publicada como votación.' : 'Propuesta rechazada.'); router.refresh(); }
  async function closeActivePoll() { if (!activePoll || !confirm('¿Deseas cerrar esta votación?')) return; const { error: closeError } = await createClient().from('polls').update({ active: false }).eq('id', activePoll.id); if (closeError) alert(closeError.message); else router.refresh(); }

  const total = activePoll?.options.reduce((sum, option) => sum + option.votes, 0) ?? 0;
  return <section className="app-view active" id="view-votaciones">
    <header className="view-header"><div><span className="view-subtitle">Consultas Ciudadanas Barriales</span><h2 className="view-title">Votaciones Digitales</h2></div><div className="view-actions"><button className="tour-help-btn"><span>?</span><span>Guía</span></button><button className="btn btn-primary" onClick={() => { setError(''); setShowModal(true); }}>{isDirigente ? '＋ Crear Nueva Votación' : '＋ Proponer Votación'}</button></div></header>
    {proposalMessage && <p className={proposalMessage.includes('No fue posible') || proposalMessage.includes('existe') ? 'form-error' : 'form-help'}>{proposalMessage}</p>}
    <div className="polls-container">
      {activePoll ? <article className="poll-widget active-poll-widget card shadow-box"><div className="poll-badge-wrapper"><span className="poll-status-badge active-badge">● CONSULTA ACTIVA</span>{isDirigente && <button className="btn btn-sm btn-ghost" onClick={closeActivePoll}>Cerrar votación</button>}</div><h3 className="poll-title">{activePoll.title}</h3><p className="poll-description">{activePoll.description}</p>
        {!activePoll.hasVoted ? <form className="voting-form" onSubmit={handleVote}><div className="poll-options-container">{activePoll.options.map((option) => <label className={`poll-option-card ${selected === option.id ? 'selected' : ''}`} key={option.id}><input className="poll-option-input" type="radio" name="pollOption" value={option.id} checked={selected === option.id} onChange={() => setSelected(option.id)} /><span className="poll-option-indicator"/><span className="poll-option-text">{option.text}</span></label>)}</div><div className="vote-action-box"><button className="btn btn-primary btn-lg" disabled={!selected || voting}>{voting ? 'Registrando…' : 'Confirmar y Emitir Mi Voto'} ✓</button></div></form> : <div className="vote-success-message visible"><strong>✔ ¡Voto registrado con éxito!</strong> Tu voto se sumó de forma segura.</div>}
        {(activePoll.hasVoted || isDirigente) && <div className="poll-results-container visible"><h4 className="results-header">Resultados en Tiempo Real</h4><div className="results-bars">{activePoll.options.map((option) => { const percentage = total ? Math.round(option.votes / total * 100) : 0; return <div className="result-bar-group" key={option.id}><div className="result-bar-labels"><span>{option.text}</span><span>{percentage}% ({option.votes} votos)</span></div><div className="result-bar-container"><div className="result-bar-fill" style={{ width: `${percentage}%` }} /></div></div>; })}</div><div className="results-meta"><span>Total de participantes: {total} vecinos</span><span className="guarantee-text">✔ Votación resguardada digitalmente</span></div></div>}
      </article> : <div className="poll-widget card shadow-box empty-state"><h3>No hay consultas activas</h3><p>Las próximas votaciones aparecerán aquí.</p></div>}
      <div className="past-polls-widget card shadow-box mt-24"><h3 className="card-title">Propuestas para la Directiva</h3><p className="card-subtitle">Los socios pueden proponer consultas; la directiva debe aprobarlas antes de publicarlas.</p><div className="past-polls-list">{proposals.map((proposal) => <article className="past-poll-row" key={proposal.id}><div className="past-poll-info"><h4 className="past-poll-title">{proposal.title}</h4><p className="past-poll-desc">{proposal.description}</p><span className={`status-badge ${proposal.status === 'approved' ? 'al-dia' : 'pendiente'}`}>{proposal.status === 'pending' ? 'Pendiente de directiva' : proposal.status === 'approved' ? 'Aprobada' : `Rechazada${proposal.rejection_reason ? `: ${proposal.rejection_reason}` : ''}`}</span></div>{isDirigente && proposal.status === 'pending' && <div className="view-actions"><button className="btn btn-sm btn-secondary danger-action" disabled={reviewingProposal === proposal.id} onClick={() => void reviewProposal(proposal, 'reject')}>Rechazar</button><button className="btn btn-sm btn-primary" disabled={reviewingProposal === proposal.id} onClick={() => void reviewProposal(proposal, 'approve')}>{reviewingProposal === proposal.id ? 'Procesando…' : 'Aprobar y publicar'}</button></div>}</article>)}{!proposals.length && <p className="empty-state">No hay propuestas registradas.</p>}</div></div>
      <div className="past-polls-widget card shadow-box mt-24"><h3 className="card-title">Historial de Consultas Anteriores</h3><div className="past-polls-list">{pastPolls.map((poll) => { const pollTotal = poll.options.reduce((sum, option) => sum + option.votes, 0); const winner = [...poll.options].sort((a, b) => b.votes - a.votes)[0]; return <article className="past-poll-row" key={poll.id}><div className="past-poll-info"><h4 className="past-poll-title">{poll.title}</h4><p className="past-poll-desc">{poll.description}</p>{winner && pollTotal > 0 && <span className="past-poll-winner">★ Resultado: {winner.text}</span>}</div><div className="date-badge">{pollTotal} votos</div></article>; })}{!pastPolls.length && <p className="empty-state">Aún no hay consultas anteriores.</p>}</div></div>
    </div>
    {showModal && <div className="modal active" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content"><div className="modal-header"><h3 className="modal-title">{isDirigente ? 'Crear Nueva Votación' : 'Proponer Votación a la Directiva'}</h3><button className="modal-close" onClick={() => setShowModal(false)}>×</button></div><div className="modal-body">{!isDirigente && <p className="card-subtitle">La propuesta no se publicará hasta que la directiva la revise y apruebe.</p>}<form onSubmit={handleCreatePoll}><div className="form-group"><label className="form-label">Pregunta o título</label><input name="title" className="form-input" minLength={5} maxLength={160} required /></div><div className="form-group"><label className="form-label">Contexto</label><textarea name="description" className="form-input" rows={4} minLength={10} required /></div><fieldset><legend className="form-label">Alternativas</legend>{options.map((option, index) => <div className="poll-option-editor" key={index}><input className="form-input" value={option} onChange={(event) => setOptions((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} required={index < 2} placeholder={`Alternativa ${index + 1}`} />{options.length > 2 && <button type="button" className="btn btn-ghost" onClick={() => setOptions((current) => current.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}{options.length < 6 && <button type="button" className="btn btn-sm btn-ghost" onClick={() => setOptions((current) => [...current, ''])}>＋ Agregar alternativa</button>}</fieldset>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><button type="button" className="btn btn-ghost" onClick={() => setShowModal(false)}>Cancelar</button><button className="btn btn-primary" disabled={loading}>{loading ? (isDirigente ? 'Publicando…' : 'Enviando…') : (isDirigente ? 'Publicar Consulta' : 'Enviar Propuesta')}</button></div></form></div></div></div></div>}
  </section>;
}
