'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { Profile, Transaction, TreasuryDocument } from '@/lib/types';
import CashflowChart from './CashflowChart';
import ExpenseChart from './ExpenseChart';

export default function TesoreriaClient({ transactions, documents, currentProfile, totalMembers, paidMembers }: { transactions: Transaction[]; documents: TreasuryDocument[]; currentProfile: Profile; totalMembers: number; paidMembers: number }) {
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(false);
  const [documentLoading, setDocumentLoading] = useState(false);
  const [documentError, setDocumentError] = useState('');
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [paymentLoading, setPaymentLoading] = useState(false);
  const [paymentError, setPaymentError] = useState('');
  const [paymentReceipt, setPaymentReceipt] = useState<{ transactionId: string; date: string; method: string } | null>(null);
  const [reportOpen, setReportOpen] = useState(false);
  const [reminderMessage, setReminderMessage] = useState('');
  const router = useRouter();
  const isDirigente = currentProfile.role === 'dirigente';
  const stats = useMemo(() => { const income = transactions.filter((t) => t.type === 'ingreso').reduce((sum, t) => sum + Number(t.amount), 0); const expenses = transactions.filter((t) => t.type === 'egreso').reduce((sum, t) => sum + Number(t.amount), 0); return { income, expenses, balance: income - expenses }; }, [transactions]);

  async function handleAddTransaction(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); const form = new FormData(event.currentTarget);
    const { error } = await createClient().from('transactions').insert({ type: form.get('type'), description: form.get('description'), amount: Number(form.get('amount')), date: form.get('date'), junta_id: currentProfile.junta_id, created_by: currentProfile.id });
    if (!error) { setShowModal(false); router.refresh(); } setLoading(false);
  }

  async function uploadDocument(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return; setDocumentError('');
    if (file.size > 10 * 1024 * 1024) { setDocumentError('El archivo no puede superar 10 MB.'); return; }
    if (!['application/pdf', 'image/jpeg', 'image/png'].includes(file.type)) { setDocumentError('Solo se permiten archivos PDF, JPG o PNG.'); return; }
    setDocumentLoading(true); const safeName = file.name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${currentProfile.junta_id}/${crypto.randomUUID()}-${safeName}`;
    const { error } = await createClient().storage.from('transparency_reports').upload(path, file);
    if (error) setDocumentError(error.message); else router.refresh(); setDocumentLoading(false); event.target.value = '';
  }

  async function deleteDocument(path: string) { if (!confirm('¿Deseas eliminar este documento?')) return; const { error } = await createClient().storage.from('transparency_reports').remove([path]); if (error) setDocumentError(error.message); else router.refresh(); }

  async function simulatePayment(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPaymentLoading(true); setPaymentError(''); const form = new FormData(event.currentTarget); const response = await fetch('/api/payments/simulate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method: form.get('method') }) }); const result = await response.json(); if (!response.ok) setPaymentError(result.error ?? 'No fue posible procesar el pago.'); else { setPaymentReceipt(result); router.refresh(); } setPaymentLoading(false); }
  async function sendReminders() { setReminderMessage('Enviando…'); const response = await fetch('/api/notifications/push', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'cuota', title: 'Recordatorio de Cuota Social', message: 'Tu cuota social se encuentra pendiente. Ingresa a JuntAPP para revisar o simular el pago.', action: '/tesoreria', onlyPending: true }) }); const result = await response.json(); setReminderMessage(response.ok ? `Avisos enviados a ${result.delivered} socios pendientes.` : (result.error ?? 'No fue posible enviar los avisos.')); }

  return <section className="app-view active" id="view-tesoreria">
    <header className="view-header"><div><span className="view-subtitle">Transparencia y Cuentas Claras</span><h2 className="view-title">Tesorería Transparente</h2></div><div className="view-actions"><button className="tour-help-btn"><span>?</span><span>Guía</span></button><button className="btn btn-ghost" onClick={() => setReportOpen(true)}>Generar Reporte Mensual</button>{isDirigente && <button className="btn btn-primary" onClick={() => setShowModal(true)}>＋ Registrar Movimiento</button>}</div></header>

    <div className="treasury-stats-grid"><div className="t-stat-card total-balance"><span className="t-stat-label">Caja Disponible Actual</span><h3 className="t-stat-value">{formatCurrency(stats.balance)}</h3><span className="t-stat-desc">Fondo para emergencias y obras</span></div><div className="t-stat-card text-success-card"><span className="t-stat-label">Ingresos Totales</span><h3 className="t-stat-value">+{formatCurrency(stats.income)}</h3><span className="t-stat-desc">Cuotas y aportes registrados</span></div><div className="t-stat-card text-danger-card"><span className="t-stat-label">Gastos Totales</span><h3 className="t-stat-value">-{formatCurrency(stats.expenses)}</h3><span className="t-stat-desc">Egresos rendidos por la directiva</span></div></div>

    <div className="charts-grid mt-24 mb-24"><div className="chart-card card shadow-box"><h3 className="card-title">Distribución de Egresos</h3><p className="card-subtitle">Clasificación de los gastos registrados</p><div className="chart-container"><ExpenseChart transactions={transactions} /></div></div><div className="chart-card card shadow-box"><h3 className="card-title">Flujo de Caja Mensual</h3><p className="card-subtitle">Comparativa histórica de ingresos y egresos</p><div className="chart-container"><CashflowChart transactions={transactions} /></div></div></div>

    <div className="split-grid"><div className="split-card main-split shadow-box"><div className="card-header"><h3 className="card-title">Libro de Caja Reciente</h3></div><div className="ledger-table-wrapper"><table className="ledger-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Concepto / Descripción</th><th className="text-right">Monto (CLP)</th></tr></thead><tbody>{transactions.map((tx) => <tr key={tx.id}><td>{formatDate(tx.date)}</td><td><span className={`transaction-type ${tx.type}`}>{tx.type === 'ingreso' ? 'Ingreso' : 'Egreso'}</span></td><td>{tx.description}</td><td className={`text-right amount-${tx.type}`}>{tx.type === 'ingreso' ? '+' : '-'}{formatCurrency(Number(tx.amount))}</td></tr>)}</tbody></table>{!transactions.length && <p className="empty-state">No hay movimientos registrados.</p>}</div></div><div className="split-card side-split shadow-box"><h3 className="card-title">Recaudación de Cuotas Sociales</h3><p className="card-subtitle">La recaudación sostiene las actividades y mantenciones de la comunidad.</p><div className="cuota-progress-box"><div className="cuota-progress-bar-container"><div className="cuota-progress-bar-fill" style={{ width: `${totalMembers ? Math.round(paidMembers / totalMembers * 100) : 0}%` }} /></div><div className="cuota-progress-meta"><span className="cuota-progress-text">{paidMembers} de {totalMembers} socios al día ({totalMembers ? Math.round(paidMembers / totalMembers * 100) : 0}%)</span></div></div><div className={`payment-status-badge ${currentProfile.cuota_status === 'al_dia' ? 'paid' : 'outstanding'}`}><span>Tu estado: <strong>{currentProfile.cuota_status === 'al_dia' ? 'Al Día' : 'Pendiente'}</strong></span></div>{!isDirigente && currentProfile.cuota_status !== 'al_dia' && <button className="btn btn-primary btn-block btn-lg" onClick={() => { setPaymentReceipt(null); setPaymentOpen(true); }}>Pagar Cuota con Webpay/Flow</button>}{isDirigente && <><button className="btn btn-secondary btn-block" onClick={sendReminders}>Enviar Recordatorios de Cuota</button>{reminderMessage && <p className="form-help">{reminderMessage}</p>}</>}</div></div>

    <div className="document-center mt-32 card shadow-box"><div className="card-header document-center-header"><div><h3 className="card-title">Repositorio de Transparencia</h3><p className="card-subtitle">Documentos oficiales, actas, rendiciones y cartolas digitalizadas</p></div>{isDirigente && <label className="btn btn-secondary btn-sm document-upload">{documentLoading ? 'Subiendo…' : 'Subir Documento'}<input type="file" accept=".pdf,.jpg,.jpeg,.png" disabled={documentLoading} onChange={uploadDocument} hidden /></label>}</div>{documentError && <p className="form-error">{documentError}</p>}<div className="document-grid">{documents.map((document) => <article className="document-card" key={document.path}><div className="document-icon">📄</div><div className="document-info"><h4>{document.name}</h4><span>{formatFileSize(document.size)}{document.created_at ? ` · ${formatDate(document.created_at)}` : ''}</span></div><div className="document-actions">{document.signedUrl && <a className="btn btn-sm btn-ghost" href={document.signedUrl} target="_blank" rel="noreferrer">Ver</a>}{isDirigente && <button className="btn btn-sm btn-secondary danger-action" onClick={() => deleteDocument(document.path)}>Eliminar</button>}</div></article>)}{!documents.length && <p className="empty-state">No hay documentos publicados.</p>}</div></div>

    {showModal && <div className="modal active" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content"><div className="modal-header"><h3 className="modal-title">Registrar Movimiento</h3><button className="modal-close" onClick={() => setShowModal(false)}>×</button></div><div className="modal-body"><form onSubmit={handleAddTransaction}><div className="form-group"><label className="form-label">Tipo</label><select name="type" className="form-input" required><option value="ingreso">Ingreso</option><option value="egreso">Egreso</option></select></div><div className="form-group"><label className="form-label">Descripción</label><input name="description" className="form-input" required /></div><div className="form-row"><div className="form-group"><label className="form-label">Monto</label><input name="amount" type="number" min="1" className="form-input" required /></div><div className="form-group"><label className="form-label">Fecha</label><input name="date" type="date" defaultValue={new Date().toISOString().split('T')[0]} className="form-input" required /></div></div><div className="modal-footer"><button type="button" className="btn btn-ghost" onClick={() => setShowModal(false)}>Cancelar</button><button type="submit" className="btn btn-primary" disabled={loading}>{loading ? 'Guardando…' : 'Registrar Movimiento'}</button></div></form></div></div></div></div>}
    {paymentOpen && <div className="modal active payment-modal" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content secure-payment-content"><div className="modal-header"><h3 className="modal-title">Portal de Pago Seguro</h3><button className="modal-close" onClick={() => setPaymentOpen(false)}>×</button></div><div className="payment-body">{paymentReceipt ? <div className="payment-step active payment-success"><div className="success-check">✓</div><h3>Transacción Aprobada</h3><p>Tu cuota quedó registrada y tu estado ya está al día.</p><div className="payment-invoice-card"><strong>Comprobante {paymentReceipt.transactionId}</strong><span>{paymentReceipt.date}</span><span>{paymentReceipt.method}</span><span>Total pagado: $5.000 CLP</span></div><button className="btn btn-primary btn-block" onClick={() => setPaymentOpen(false)}>Cerrar Comprobante</button></div> : <form className="payment-step active" onSubmit={simulatePayment}><div className="payment-header-brand"><h3>Pago de Cuota Social</h3><span>Simulador seguro</span></div><div className="payment-invoice-card"><span>Socio</span><strong>{currentProfile.name}</strong><span>Total a pagar</span><strong>$5.000 CLP</strong></div><div className="form-group"><label className="form-label">Método de pago</label><select className="form-input" name="method"><option value="webpay">Webpay Plus (Débito)</option><option value="transfer">Transferencia Electrónica</option><option value="digital">Pago Móvil</option></select></div><p className="payment-simulator-note">Este es el simulador de capacitación incluido en el repositorio; no solicita datos bancarios reales.</p>{paymentError && <p className="form-error">{paymentError}</p>}<button type="submit" className="btn btn-primary btn-block btn-lg" disabled={paymentLoading}>{paymentLoading ? 'Procesando…' : 'Simular Pago Seguro'}</button></form>}</div></div></div></div>}
    {reportOpen && <div className="modal active report-modal" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content"><div className="modal-header"><h3 className="modal-title">Reporte Mensual de Tesorería</h3><button className="modal-close" onClick={() => setReportOpen(false)}>×</button></div><div className="modal-body"><div className="report-summary-row income"><span>Ingresos</span><strong>{formatCurrency(stats.income)}</strong></div><div className="report-summary-row expense"><span>Egresos</span><strong>{formatCurrency(stats.expenses)}</strong></div><div className="report-summary-row"><span>Balance</span><strong>{formatCurrency(stats.balance)}</strong></div><p className="card-subtitle">El reporte incluye {transactions.length} movimientos y {documents.length} documentos de respaldo.</p></div><div className="modal-footer"><button className="btn btn-ghost" onClick={() => setReportOpen(false)}>Cerrar</button><button className="btn btn-primary" onClick={() => window.print()}>Imprimir / Guardar PDF</button></div></div></div></div>}
  </section>;
}

function formatFileSize(bytes: number) { if (!bytes) return 'Tamaño desconocido'; if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
