-- JuntAPP Database Initialization Schema
-- Created on Mayo 2026

-- Enable UUID extension if not present
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 👥 1. PROFILES / SOCIOS TABLE
-- ==========================================
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    rut TEXT UNIQUE NOT NULL,
    address TEXT NOT NULL,
    phone TEXT,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('vecino', 'dirigente')) DEFAULT 'vecino',
    cuota_status TEXT NOT NULL CHECK (cuota_status IN ('al_dia', 'pendiente')) DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are readable by authenticated users" 
ON public.profiles FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Profiles are updatable by dirigentes or owner" 
ON public.profiles FOR UPDATE 
TO authenticated 
USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente'
    OR id = auth.uid()
) 
WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente'
    OR id = auth.uid()
);

CREATE POLICY "Profiles can be inserted by dirigentes or registration" 
ON public.profiles FOR INSERT 
TO authenticated 
WITH CHECK (true); -- Registrations are managed via trigger or client

CREATE POLICY "Profiles can be deleted by dirigentes" 
ON public.profiles FOR DELETE 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');


-- ==========================================
-- 💵 2. TRANSACTIONS / LIBRO DE CAJA TABLE
-- ==========================================
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('ingreso', 'egreso')),
    description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Transactions Policies
CREATE POLICY "Transactions are readable by authenticated users" 
ON public.transactions FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Transactions can be inserted by dirigentes" 
ON public.transactions FOR INSERT 
TO authenticated 
WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');

CREATE POLICY "Transactions can be updated by dirigentes" 
ON public.transactions FOR UPDATE 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente')
WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');

CREATE POLICY "Transactions can be deleted by dirigentes" 
ON public.transactions FOR DELETE 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');


-- ==========================================
-- 🗳️ 3. POLLS / CONSULTAS TABLE
-- ==========================================
CREATE TABLE public.polls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    options JSONB NOT NULL, -- Format: [{"id": "opt-1", "text": "Camaras"}]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.polls ENABLE ROW LEVEL SECURITY;

-- Polls Policies
CREATE POLICY "Polls are readable by authenticated users" 
ON public.polls FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Polls can be managed by dirigentes" 
ON public.polls FOR ALL 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');


-- ==========================================
-- 🗳️ 4. VOTES TABLE (Tracks individual votes)
-- ==========================================
CREATE TABLE public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    poll_id UUID REFERENCES public.polls(id) ON DELETE CASCADE,
    option_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, poll_id) -- One vote per user per poll
);

-- Enable Row Level Security
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;

-- Votes Policies
CREATE POLICY "Votes count readable by authenticated users" 
ON public.votes FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Users can insert their own vote" 
ON public.votes FOR INSERT 
TO authenticated 
WITH CHECK (user_id = auth.uid());


-- ==========================================
-- 📢 5. ANNOUNCEMENTS / COMUNICADOS TABLE
-- ==========================================
CREATE TABLE public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('urgente', 'asamblea', 'beneficio', 'general')),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    author TEXT NOT NULL DEFAULT 'Directiva JuntAPP',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Announcements Policies
CREATE POLICY "Announcements are readable by authenticated users" 
ON public.announcements FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Announcements can be managed by dirigentes" 
ON public.announcements FOR ALL 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente');


-- ==========================================
-- 🔔 6. NOTIFICATIONS / AVISOS TABLE
-- ==========================================
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('asamblea', 'votacion', 'cuota', 'seguridad')),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN NOT NULL DEFAULT false,
    date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    action TEXT,
    target_socio_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Notifications Policies
CREATE POLICY "Users can view and update their own notifications" 
ON public.notifications FOR ALL 
TO authenticated 
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "System or Dirigentes can insert notifications" 
ON public.notifications FOR INSERT 
TO authenticated 
WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'dirigente'
    OR auth.uid() IS NOT NULL -- Allow system functions
);


-- ==========================================
-- 🔄 7. TRIGGERS: SYNC AUTH USERS -> PROFILES
-- ==========================================

-- Function to handle new user registrations
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    default_role TEXT := 'vecino';
    default_cuota TEXT := 'pendiente';
BEGIN
    -- Determine role by email domain or metadata if needed
    -- For convenience, admin@juntapp.cl is seeded as 'dirigente'
    IF NEW.email = 'admin@juntapp.cl' OR NEW.email = 'dirigente@juntapp.cl' THEN
        default_role := 'dirigente';
        default_cuota := 'al_dia';
    END IF;

    INSERT INTO public.profiles (id, name, rut, address, phone, email, role, cuota_status)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', 'Nuevo Vecino'),
        COALESCE(NEW.raw_user_meta_data->>'rut', '11.111.111-1'),
        COALESCE(NEW.raw_user_meta_data->>'address', 'Sin Dirección'),
        COALESCE(NEW.raw_user_meta_data->>'phone', ''),
        NEW.email,
        default_role,
        default_cuota
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
